### ISSUE TITLE
Cannot run the code due to version issues

### ISSUE THREAD

**Issue by prerna-grg** [KupynOrest/DeblurGAN#133]
@KupynOrest 
If i run your code using torch 0.3.1 , torchtext 0.2.3 , then I get the error **AttributeError: module 'torch' has no attribute 'float32'**

As suggested by various sources online, to solve this I change torch version to 0.4, then I get the error **Unexpected running stats buffer(s) "model.23.running_mean" and "model.23.running_var" for InstanceNorm2d with track_running_stats=False.** to which other sources say to change the torch version to 0.3.1

So I am stuck, Could you please tell what versions you used to run your code??

**Comment by SivanDoveh** [comment]
Undo all NINJA changes and it will work with torch 0.3.1. 
It worked for me

**Comment by JhonKS** [comment]
I have same problem.
Did you solve that issue? If yes, could you tell in detail?
I run deblurGAN on python3.5 + cuda8 + pytorch0.4.0.

**Comment by QuantScientist** [comment]
Same here:
What do you mean by "Undo all NINJA changes"?

**Comment by vlee-harmonicinc** [comment]
I also have this issue with pyTorch 0.3.1 and torchvision 0.2.2.post3
This fixed by downgrading torchvision to 0.2.0.
